site:
  title: Moj Docs Portal (lokalno)
  start_page: mydocs::index.adoc

content:
  sources:
    - url: .
      start_path: docs-site
      branches: HEAD

asciidoc:
  attributes:
    page-pagination: true

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=build

output:
  dir: public
